# Generated by Django 4.1 on 2022-10-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invadeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='champions',
            name='image',
            field=models.CharField(default='meh', max_length=100),
        ),
    ]
