# Generated by Django 4.1 on 2022-10-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invadeapp', '0003_playerrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_data', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='playerrecord',
            name='eid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
