# Generated by Django 4.1 on 2022-10-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invadeapp', '0007_matchdata_championid_matchdata_summonername'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alldata', models.CharField(blank=True, max_length=100000000, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='matchdata',
            old_name='championId',
            new_name='champion_Id',
        ),
        migrations.RenameField(
            model_name='matchdata',
            old_name='summonerName',
            new_name='summoner_Name',
        ),
    ]
