# Generated by Django 4.1 on 2022-11-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invadeapp', '0007_remove_matchdata_map_id_matchdata_champion_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdata',
            name='team_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
