# Generated by Django 4.1 on 2022-11-01 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invadeapp', '0008_matchdata_team_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchdata',
            name='game_id',
        ),
    ]
