# Generated by Django 4.1 on 2022-11-02 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invadeapp', '0009_remove_matchdata_game_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchdata',
            old_name='summonerName',
            new_name='summoner_name',
        ),
    ]
