# Generated by Django 4.1 on 2022-11-02 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invadeapp', '0010_rename_summonername_matchdata_summoner_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchdata',
            old_name='summoner_name',
            new_name='summoner_name_match',
        ),
    ]
